apiVersion: v1
kind: Service
metadata:
  name: edge-agent
  namespace: edge-agent
  labels:
    app: edge-agent
spec:
  type: NodePort
  selector:
    app: edge-agent
  ports:
    - port: 30080
      targetPort: 30080
      nodePort: 30080
      protocol: TCP
